# Generated by Django 4.1.7 on 2026-02-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='total_calories',
            field=models.IntegerField(default=0),
        ),
    ]
