# Generated by Django 4.1.7 on 2026-02-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0003_leaderboard_total_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
